name: UnityBuildTest
run-name: Unity Build Test

on: workflow_dispatch

permissions: write-all

jobs:
  buildForAndroid: 
    name: Build Android
    runs-on: ubuntu-latest
    steps:

      # Step1 - Check Out
      - name: Check Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Step2 - Unity Build
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          unityVersion: 2022.3.1f1
          customBuildPath: build

      # Step3 - Upload Build File
      - name: Upload Build File
        uses: actions/upload-artifact@v3
        with:
          name: Build-Android
          path: build
